# Generated by Django 4.2.2 on 2023-06-17 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardiologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1)),
                ('brief_info', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('g', 'General cardiology'), ('c', 'Cardiac electrophysiology'), ('e', 'Echocardiography'), ('h', 'Heart failure and transplant cardiology')], default='g', max_length=1)),
                ('phone_number', models.CharField(max_length=14)),
                ('experience', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('phone_number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1)),
                ('insurance_details', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('cardiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.cardiologist')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('r', 'Ready'), ('n', 'Not Ready'), ('c', 'Completed')], default='n', max_length=1)),
                ('cardiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.cardiologist')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('cardiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.cardiologist')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.patient')),
            ],
        ),
    ]
