# Generated by Django 4.2.2 on 2023-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiologyDepartment', '0002_alter_cardiologist_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='due_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cardiologist',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='cardiologist',
            name='specialization',
            field=models.CharField(choices=[('G', 'General cardiology'), ('C', 'Cardiac electrophysiology'), ('E', 'Echocardiography'), ('H', 'Heart failure and transplant cardiology')], default='G', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
