# Generated by Django 4.2.2 on 2023-06-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiologyDepartment', '0004_alter_test_cost_alter_test_name_alter_test_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
