# Generated by Django 4.2.2 on 2023-06-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiologyDepartment', '0005_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('cost', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(choices=[('R', 'Ready'), ('N', 'Not Ready'), ('C', 'Completed')], default='N', max_length=1)),
                ('cardiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.cardiologist')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radiologyDepartment.patient')),
            ],
        ),
    ]
