# Generated by Django 4.2.2 on 2023-06-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiologyDepartment', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
